### ISSUE TITLE
pause playback when headphones are unplugged

### ISSUE THREAD

**Issue by predator8bit** [no-go/HaveRadiosion#3]
Almost all music players have this as a default, so I was pretty surprised when I unplugged my earbuds and the music kept playing with this app.

**Comment by alltagshack** [comment]
Hi. You are right. I think stop-playing should be the default behavior. I build a version 2.6 in the last hour to detect headphone interaction. I am sorry: I only detect "plug out AND plug in" - both stops the player now. If you use a bluetooth headphone, I detect only plug off.

I hope, this is a usable workaround for you :o)
